project_id = "need-this-later"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000", "http://localhost:5173"]
enable_signup = true
minimum_password_length = 10

[storage]
enabled = true
file_size_limit = "25MiB"
